-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 14:26:28
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = false,
		["Slot1"] = "ITM_APPLE",
		["Slot10"] = "ITM_CARROT",
		["Slot11"] = "ITM_PANACEA",
		["Slot12"] = "",
		["Slot13"] = "",
		["Slot14"] = "",
		["Slot15"] = "",
		["Slot16"] = "",
		["Slot17"] = "",
		["Slot18"] = "",
		["Slot19"] = "",
		["Slot2"] = "ITM_SALVE",
		["Slot20"] = "",
		["Slot3"] = "ITM_POTION",
		["Slot4"] = "ITM_HEALINGHERB",
		["Slot5"] = "ITM_ANTIDOTE",
		["Slot6"] = "ITM_MEDICINE",
		["Slot7"] = "ITM_MAGICDUST",
		["Slot8"] = "ITM_VOICEHERB",
		["Slot9"] = "ITM_MANDRAKE",
		["Title"] = "Emor Shylah's item shop"}

return ret
