-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 14:26:28
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = false,
		["Slot1"] = "ITM_APPLE",
		["Slot10"] = "",
		["Slot11"] = "",
		["Slot12"] = "",
		["Slot13"] = "",
		["Slot14"] = "",
		["Slot15"] = "",
		["Slot16"] = "",
		["Slot17"] = "",
		["Slot18"] = "",
		["Slot19"] = "",
		["Slot2"] = "ITM_SALVE",
		["Slot20"] = "ITM_FLAMEORB",
		["Slot3"] = "ITM_MEDICINE",
		["Slot4"] = "ITM_ANTIDOTE",
		["Slot5"] = "ITM_MAGICDUST",
		["Slot6"] = "ITM_MANDRAKE",
		["Slot7"] = "ITM_BELL",
		["Slot8"] = "",
		["Slot9"] = "",
		["Title"] = "Wanda's item shop"}

return ret
