-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 16:26:06
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = true,
		["Slot1"] = "WAND_II_EVIL",
		["Slot10"] = "WAND_THUNDER",
		["Slot11"] = "WAND_SPLASH",
		["Slot12"] = "WAND_HOLY",
		["Slot13"] = "WAND_GAIA",
		["Slot14"] = "WAND_FROST",
		["Slot15"] = "WAND_FLAME",
		["Slot16"] = "WAND_DARK",
		["Slot17"] = "WAND_BIO",
		["Slot18"] = "",
		["Slot19"] = "",
		["Slot2"] = "WAND_II_GAIA",
		["Slot20"] = "",
		["Slot3"] = "WAND_II_HURRICANE",
		["Slot4"] = "WAND_II_KELVIN",
		["Slot5"] = "WAND_II_SAINT",
		["Slot6"] = "WAND_II_SPRINGTIJ",
		["Slot7"] = "WAND_II_VOLCANOWAND",
		["Slot8"] = "WAND_II_WATT",
		["Slot9"] = "WAND_WIND",
		["Title"] = "Yllabonja's Wand Store"}

return ret
