-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 14:26:28
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = false,
		["Slot1"] = "EQP_JAKE_WP6",
		["Slot10"] = "EQP_DANDOR_WP6",
		["Slot11"] = "EQP_DANDOR_WP5",
		["Slot12"] = "EQP_DANDOR_WP4",
		["Slot13"] = "EQP_HANDOSTILLOR_WP6",
		["Slot14"] = "EQP_HANDOSTILLOR_WP5",
		["Slot15"] = "EQP_HANDOSTILLOR_WP4",
		["Slot16"] = "EQP_HANDOSTILLOR_AR6",
		["Slot17"] = "EQP_HANDOSTILLOR_AR5",
		["Slot18"] = "EQP_HANDOSTILLOR_AR4",
		["Slot19"] = "EQP_ACC_TITANBELT",
		["Slot2"] = "EQP_JAKE_WP5",
		["Slot20"] = "ITM_VOLTABALL",
		["Slot3"] = "EQP_JAKE_WP4",
		["Slot4"] = "EQP_JAKE_AR6",
		["Slot5"] = "EQP_JAKE_AR5",
		["Slot6"] = "EQP_JAKE_AR4",
		["Slot7"] = "EQP_MARRILONA_AR6",
		["Slot8"] = "EQP_MARRILONA_AR5",
		["Slot9"] = "EQP_MARRILONA_AR4",
		["Title"] = ""}

return ret
