-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 16:26:06
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = true,
		["Slot1"] = "EQP_JAKE_WP7",
		["Slot10"] = "EQP_DANDOR_WP7",
		["Slot11"] = "EQP_DANDOR_WP6",
		["Slot12"] = "EQP_DANDOR_WP5",
		["Slot13"] = "EQP_HANDOSTILLOR_WP7",
		["Slot14"] = "EQP_HANDOSTILLOR_WP6",
		["Slot15"] = "EQP_HANDOSTILLOR_WP5",
		["Slot16"] = "EQP_HANDOSTILLOR_AR7",
		["Slot17"] = "EQP_HANDOSTILLOR_AR6",
		["Slot18"] = "EQP_HANDOSTILLOR_AR5",
		["Slot19"] = "EQP_JEWEL_SMALLEMERALD",
		["Slot2"] = "EQP_JAKE_WP6",
		["Slot20"] = "EQP_JEWEL_SMALLTOPAZ",
		["Slot3"] = "EQP_JAKE_WP5",
		["Slot4"] = "EQP_JAKE_AR7",
		["Slot5"] = "EQP_JAKE_AR6",
		["Slot6"] = "EQP_JAKE_AR5",
		["Slot7"] = "EQP_MARRILONA_AR7",
		["Slot8"] = "EQP_MARRILONA_AR6",
		["Slot9"] = "EQP_MARRILONA_AR5",
		["Title"] = "Nathalia's weapon Sotre"}

return ret
