-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 16:26:06
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = false,
		["Slot1"] = "EQP_JAKE_WP3",
		["Slot10"] = "EQP_JAKE_AR3",
		["Slot11"] = "EQP_JAKE_AR4",
		["Slot12"] = "EQP_JAKE_AR5",
		["Slot13"] = "EQP_MARRILONA_AR3",
		["Slot14"] = "EQP_MARRILONA_AR4",
		["Slot15"] = "EQP_MARRILONA_AR5",
		["Slot16"] = "EQP_HANDOSTILLOR_AR3",
		["Slot17"] = "EQP_HANDOSTILLOR_AR4",
		["Slot18"] = "EQP_HANDOSTILLOR_AR5",
		["Slot19"] = "ITM_BELL",
		["Slot2"] = "EQP_JAKE_WP4",
		["Slot20"] = "ITM_PURELITERATURE",
		["Slot3"] = "EQP_JAKE_WP5",
		["Slot4"] = "EQP_DANDOR_WP3",
		["Slot5"] = "EQP_DANDOR_WP4",
		["Slot6"] = "EQP_DANDOR_WP5",
		["Slot7"] = "EQP_HANDOSTILLOR_WP3",
		["Slot8"] = "EQP_HANDOSTILLOR_WP4",
		["Slot9"] = "EQP_HANDOSTILLOR_WP5",
		["Title"] = ""}

return ret
