-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 14:26:28
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = true,
		["Slot1"] = "EQP_JAKE_WP2",
		["Slot10"] = "EQP_DANDOR_WP2",
		["Slot11"] = "EQP_DANDOR_WP3",
		["Slot12"] = "EQP_DANDOR_WP4",
		["Slot13"] = "EQP_HANDOSTILLOR_WP2",
		["Slot14"] = "EQP_HANDOSTILLOR_WP3",
		["Slot15"] = "EQP_HANDOSTILLOR_WP4",
		["Slot16"] = "EQP_HANDOSTILLOR_AR2",
		["Slot17"] = "EQP_HANDOSTILLOR_AR3",
		["Slot18"] = "EQP_HANDOSTILLOR_AR4",
		["Slot19"] = "ITM_PHOENIX",
		["Slot2"] = "EQP_JAKE_WP3",
		["Slot20"] = "ITM_SALVE",
		["Slot3"] = "EQP_JAKE_WP4",
		["Slot4"] = "EQP_JAKE_AR2",
		["Slot5"] = "EQP_JAKE_AR3",
		["Slot6"] = "EQP_JAKE_AR4",
		["Slot7"] = "EQP_MARRILONA_AR2",
		["Slot8"] = "EQP_MARRILONA_AR3",
		["Slot9"] = "EQP_MARRILONA_AR4",
		["Title"] = "Myra Remembo's weapon shop"}

return ret
