-- This file has be generated by Tricky's MyData
-- 25 Mar 2017; 16:26:06
-- License: This file contains data from the Phantasar Universe and is therefore property of Jeroen Broks and may NOT be used for your own ends.
	ret = {
		["AllowTrade"] = false,
		["Slot1"] = "EQP_JAKE_WP2",
		["Slot10"] = "AAA_ATTACK",
		["Slot11"] = "AAA_ATTACK",
		["Slot12"] = "AAA_ATTACK",
		["Slot13"] = "AAA_ATTACK",
		["Slot14"] = "AAA_ATTACK",
		["Slot15"] = "AAA_ATTACK",
		["Slot16"] = "AAA_ATTACK",
		["Slot17"] = "AAA_ATTACK",
		["Slot18"] = "AAA_ATTACK",
		["Slot19"] = "AAA_ATTACK",
		["Slot2"] = "EQP_DANDOR_WP2",
		["Slot20"] = "AAA_ATTACK",
		["Slot3"] = "EQP_HANDOSTILLOR_WP2",
		["Slot4"] = "EQP_JAKE_AR2",
		["Slot5"] = "EQP_MARRILONA_AR2",
		["Slot6"] = "EQP_HANDOSTILLOR_WP2",
		["Slot7"] = "ITM_SALVE",
		["Slot8"] = "AAA_ATTACK",
		["Slot9"] = "AAA_ATTACK",
		["Title"] = "Eric's weapon Shop"}

return ret
