ret = {
	["ABL_APCost"] = 300,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 150,
	["ADDCARD_Char_Number"] = 1,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Accuracy"] = 5,
	["BUFF_Endurance"] = 5,
	["BUFF_Evasion"] = 5,
	["BUFF_Intelligence"] = 5,
	["BUFF_Power"] = 5,
	["BUFF_Resistance"] = 5,
	["BUFF_Speed"] = 5,
	["CauseGuarding"] = true,
	["CausePermanence"] = true,
	["CureCurse"] = true,
	["CureDisease"] = true,
	["CureParalysis"] = true,
	["CurePetrification"] = true,
	["CurePoison"] = true,
	["CureSilence"] = true,
	["CureSleep"] = true,
	["CureUndead"] = true,
	["Desc"] = "Heals everything there is to be healed",
	["Heal"] = 100,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Percent",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["Revive"] = true,
	["SpellAni"] = "SingleHeal",
	["Stance"] = "Cast",
	["Target"] = "1A",
	["Title"] = "Whizzy's Mega-Heal",
	["Type"] = "Ability",
	["Voice"] = "Weniaria",
	["rew_GainSkill2"] = 300}

return ret

-- This file is an automatically generated file!

