ret = {
	["ABL_APCost"] = 75,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 50,
	["ADDCARD_Action_Number"] = 3,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["CureCurse"] = true,
	["CureDisease"] = true,
	["CureParalysis"] = true,
	["CurePetrification"] = true,
	["CurePoison"] = true,
	["CureSilence"] = true,
	["CureSleep"] = true,
	["CureUndead"] = true,
	["Desc"] = "Heals HP and cures status changes",
	["Heal"] = 200,
	["Heal_StatPercent"] = "Power",
	["Heal_Type"] = "StatPercent",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["SpellAni"] = "Heal",
	["Stance"] = "Cast",
	["Target"] = "1A",
	["Title"] = "Heal Blade",
	["Type"] = "Ability",
	["Voice"] = "Heal",
	["rew_GainSkill1"] = 5,
	["rew_GainSkill4"] = 5,
	["rew_GainSkill5"] = 5}

return ret

-- This file is an automatically generated file!

