ret = {
	["ABL_APCost"] = 350,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 50,
	["ADDCARD_Action_Number"] = 3,
	["Attack"] = 40,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Earth",
	["CauseDeath"] = true,
	["CauseDisease"] = true,
	["CausePoison"] = true,
	["Desc"] = "It's the arockalypse, now bear your soul",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["SpellAni"] = "Quake",
	["Stance"] = "Cast",
	["Target"] = "1A",
	["Title"] = "Mega Quake",
	["Type"] = "Ability",
	["rew_GainSkill1"] = 50,
	["rew_GainSkill2"] = 100,
	["rew_GainSkill3"] = 150,
	["rew_GainSkill4"] = 200,
	["rew_GainSkill5"] = 250}

return ret

-- This file is an automatically generated file!

