ret = {
	["ABL_APCost"] = 100,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 10,
	["ADDCARD_Action_Number"] = 100,
	["Attack"] = 100,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Flame",
	["Desc"] = "Is this turn-in, an eternal flame?",
	["EQP_STAT_Intelligence"] = 1,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 250,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["SpellAni"] = "Flame",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Eternal Flame",
	["Type"] = "Ability",
	["Voice"] = "Fire",
	["rew_CreateSkill1"] = true,
	["rew_GainSkill1"] = 1,
	["rew_GainSkill2"] = 50}

return ret

-- This file is an automatically generated file!

