ret = {
	["ABL_APCost"] = 400,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 75,
	["ADDCARD_Action_Number"] = 5,
	["Attack"] = 575,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Wind",
	["CauseParalysis"] = true,
	["Desc"] = "Blow, storm! Blow!",
	["EQP_STAT_Intelligence"] = 1,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 250,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Stance"] = "Cast",
	["Target"] = "AF",
	["Title"] = "Katrina",
	["Type"] = "Ability",
	["Voice"] = "Wind",
	["rew_CreateSkill1"] = true,
	["rew_GainSkill1"] = 3,
	["rew_GainSkill2"] = 250,
	["rew_GainSkill3"] = 250,
	["rew_GainSkill4"] = 250,
	["rew_GainSkill5"] = 250}

return ret

-- This file is an automatically generated file!

