ret = {
	["ABL_APCost"] = 150,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 10,
	["ADDCARD_Action_Number"] = 3,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["CureCurse"] = true,
	["CureDisease"] = true,
	["CureParalysis"] = true,
	["CurePetrification"] = true,
	["CurePoison"] = true,
	["CureSilence"] = true,
	["CureUndead"] = true,
	["Desc"] = "A good healt is your best asset",
	["Heal"] = 10,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Percent",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["Revive"] = true,
	["Stance"] = "Cast",
	["Target"] = "AA",
	["Title"] = "Ultra-Heal",
	["Type"] = "Ability",
	["Voice"] = "Heal"}

return ret

-- This file is an automatically generated file!

