ret = {
	["ADDCARD_Action_Act"] = "EXE_MARRILONA_MEDITATION",
	["ADDCARD_Action_Interval"] = 50,
	["ADDCARD_Action_Number"] = 2,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "Wait for the magic shower",
	["EffectScript"] = "RecoverAP",
	["EffectScript_Arg"] = "1",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["Rew_GainAP"] = 1,
	["SpellAni"] = "SingleHeal",
	["Stance"] = "Cast",
	["Target"] = "OS",
	["Title"] = "Meditation",
	["Type"] = "Item",
	["Voice"] = "Heal",
	["rew_GainSkill1"] = 50,
	["rew_GainSkill2"] = 50,
	["rew_GainSkill3"] = 50,
	["rew_GainSkill4"] = 50,
	["rew_GainSkill5"] = 50}

return ret

-- This file is an automatically generated file!

