ret = {
	["ABL_APCost"] = 15,
	["ADDCARD_Action_Act"] = "Self",
	["Attack"] = 100,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Lightning",
	["Desc"] = "Electric Boogie!",
	["EQP_STAT_Intelligence"] = 1,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 250,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 5,
	["SpellAni"] = "Spark",
	["Stance"] = "Attack",
	["Target"] = "1F",
	["Title"] = "Zap!",
	["Type"] = "Ability",
	["Voice"] = "Lightning",
	["rew_CreateSkill1"] = true,
	["rew_GainSkill1"] = 5,
	["rew_GainSkill2"] = 4,
	["rew_GainSkill3"] = 4}

return ret

-- This file is an automatically generated file!

