ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Accuracy"] = -20,
	["BUFF_Endurance"] = -5,
	["BUFF_Evasion"] = -100,
	["BUFF_Intelligence"] = 5,
	["BUFF_Power"] = -1,
	["BUFF_Resistance"] = 5,
	["BUFF_Speed"] = -100,
	["Desc"] = "Gain extra AP",
	["EffectScript"] = "RecoverAP",
	["EffectScript_Arg"] = "100",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["SpellAni"] = "Heal",
	["Stance"] = "Cast",
	["Target"] = "OS",
	["Title"] = "Pray",
	["Type"] = "Ability",
	["Voice"] = "Weniaria",
	["rew_GainSkill2"] = -1}

return ret

-- This file is an automatically generated file!

