ret = {
	["ABL_APCost"] = 345,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 8,
	["ADDCARD_Action_Number"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 500,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "None",
	["CauseCurse"] = true,
	["Desc"] = "Everyone will DIE!!",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["SpellAni"] = "Inferno",
	["Stance"] = "Cast",
	["Target"] = "1A",
	["Title"] = "Catastrophe",
	["Type"] = "Ability",
	["Voice"] = "Critical",
	["rew_GainSkill1"] = 50,
	["rew_GainSkill2"] = 50,
	["rew_GainSkill3"] = 50,
	["rew_GainSkill4"] = 50,
	["rew_GainSkill5"] = 50}

return ret

-- This file is an automatically generated file!

