ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["CureCurse"] = true,
	["CureDisease"] = true,
	["CureParalysis"] = true,
	["CurePetrification"] = true,
	["CurePoison"] = true,
	["CureSilence"] = true,
	["CureSleep"] = true,
	["CureUndead"] = true,
	["Desc"] = "Heal when needed",
	["Heal"] = 100,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Percent",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["Revive"] = true,
	["SpellAni"] = "SingleHeal",
	["Stance"] = "Cast",
	["Target"] = "1A",
	["Title"] = "Emergency Heal",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

