ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "The only armor Dandor can wear and it's cool!",
	["EQP_STAT_AP"] = 25,
	["EQP_STAT_Accuracy"] = 4,
	["EQP_STAT_ER_Darkness"] = 5,
	["EQP_STAT_ER_Earth"] = 200,
	["EQP_STAT_ER_Flame"] = 5,
	["EQP_STAT_ER_Frost"] = 5,
	["EQP_STAT_ER_Light"] = 5,
	["EQP_STAT_ER_Lightning"] = 5,
	["EQP_STAT_ER_Water"] = 5,
	["EQP_STAT_ER_Wind"] = 5,
	["EQP_STAT_Endurance"] = 250,
	["EQP_STAT_Evasion"] = 5,
	["EQP_STAT_HP"] = 1500,
	["EQP_STAT_Intelligence"] = 5,
	["EQP_STAT_Power"] = 5,
	["EQP_STAT_Resistance"] = 300,
	["EQP_STAT_SR_Curse"] = 50,
	["EQP_STAT_SR_Death"] = 50,
	["EQP_STAT_SR_Destruction"] = 50,
	["EQP_STAT_SR_Disease"] = 50,
	["EQP_STAT_SR_Paralysis"] = 50,
	["EQP_STAT_SR_Petrification"] = 50,
	["EQP_STAT_SR_Poison"] = 50,
	["EQP_STAT_SR_Silence"] = 50,
	["EQP_STAT_SR_Sleep"] = 50,
	["EQP_STAT_SR_Undead"] = 50,
	["Heal_StatPercent"] = "Intelligence",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Dandor",
	["ITM_Field"] = true,
	["ITM_Type"] = "Armor",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Tyrant's Belt",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

