ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 200,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowAccuracy"] = true,
	["Attack_AllowCritical"] = true,
	["Attack_AllowDodge"] = true,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["CauseUndead"] = true,
	["Desc"] = "Drains life from undead. Great for training. Turns user into undead",
	["EQP_STAT_ER_Darkness"] = -25,
	["EQP_STAT_Evasion"] = 25,
	["EQP_STAT_Power"] = 250,
	["EffectScript"] = "Undeadbackfire",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "HandoStillor",
	["ITM_Field"] = true,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 15,
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Zombie Staff",
	["Type"] = "Item",
	["Voice"] = "Hit",
	["rew_GainSkill1"] = 15,
	["rew_GainSkill2"] = 15}

return ret

-- This file is an automatically generated file!

