ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Action_Number"] = 2,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 120,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "Light",
	["Desc"] = "The best weapon for a priest who stickfights",
	["EQP_STAT_Accuracy"] = 100,
	["EQP_STAT_Endurance"] = 5,
	["EQP_STAT_Evasion"] = 3,
	["EQP_STAT_Intelligence"] = 150,
	["EQP_STAT_Power"] = 300,
	["EQP_STAT_Resistance"] = 3,
	["EQP_STAT_SR_Curse"] = 3,
	["EQP_STAT_SR_Death"] = 3,
	["EQP_STAT_SR_Destruction"] = 3,
	["EQP_STAT_SR_Disease"] = 3,
	["EQP_STAT_SR_Paralysis"] = 3,
	["EQP_STAT_SR_Petrification"] = 3,
	["EQP_STAT_SR_Poison"] = 3,
	["EQP_STAT_SR_Silence"] = 3,
	["EQP_STAT_SR_Sleep"] = 3,
	["EQP_STAT_SR_Undead"] = 3,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "HandoStillor",
	["ITM_Field"] = true,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 25,
	["SpellAni"] = "SingleHeal",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Holy Ewp Staff",
	["Type"] = "Item",
	["Voice"] = "Holy Strike",
	["rew_GainSkill1"] = 75,
	["rew_GainSkill2"] = 75}

return ret

-- This file is an automatically generated file!

