ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Acc_PreTurn"] = "RecoverAP",
	["Acc_PreTurn_Arg"] = "50",
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "Will it really help you?",
	["EQP_STAT_AP"] = 500,
	["EQP_STAT_Accuracy"] = -10000,
	["EQP_STAT_Endurance"] = -10000,
	["EQP_STAT_Evasion"] = -10000,
	["EQP_STAT_HP"] = -500,
	["EQP_STAT_Intelligence"] = 200,
	["EQP_STAT_Power"] = -10000,
	["EQP_STAT_Resistance"] = -50,
	["EQP_STAT_SR_Curse"] = 100,
	["EQP_STAT_SR_Death"] = 100,
	["EQP_STAT_SR_Petrification"] = 100,
	["Heal_StatPercent"] = "Intelligence",
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 50000,
	["ITM_Type"] = "Accesoiry",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "The Ring Which Shall Not Be Named",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

