ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "Marrilona is hot and indestructable",
	["EQP_STAT_ER_Darkness"] = 10,
	["EQP_STAT_ER_Earth"] = 10,
	["EQP_STAT_ER_Flame"] = 10,
	["EQP_STAT_ER_Frost"] = 10,
	["EQP_STAT_ER_Light"] = 10,
	["EQP_STAT_ER_Lightning"] = 10,
	["EQP_STAT_ER_Water"] = 10,
	["EQP_STAT_ER_Wind"] = 10,
	["EQP_STAT_Endurance"] = 20,
	["EQP_STAT_Evasion"] = 20,
	["EQP_STAT_Intelligence"] = 25,
	["EQP_STAT_Resistance"] = 60,
	["EQP_STAT_SR_Curse"] = 100,
	["EQP_STAT_SR_Death"] = 10,
	["EQP_STAT_SR_Destruction"] = 10,
	["EQP_STAT_SR_Disease"] = 5,
	["EQP_STAT_SR_Paralysis"] = 10,
	["EQP_STAT_SR_Petrification"] = 10,
	["EQP_STAT_SR_Poison"] = 5,
	["EQP_STAT_SR_Silence"] = 100,
	["EQP_STAT_SR_Sleep"] = 10,
	["EQP_STAT_SR_Undead"] = 1,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Type"] = "Armor",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Sexy Magicus Miniskirt",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

