ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "These are very rare. Normally nobody uses real dragonskin.",
	["EQP_STAT_Accuracy"] = 4,
	["EQP_STAT_ER_Flame"] = 100,
	["EQP_STAT_Endurance"] = 40,
	["EQP_STAT_Evasion"] = 30,
	["EQP_STAT_Intelligence"] = 10,
	["EQP_STAT_Power"] = 5,
	["EQP_STAT_Resistance"] = 50,
	["EQP_STAT_SR_Death"] = 10,
	["EQP_STAT_SR_Destruction"] = 10,
	["EQP_STAT_SR_Disease"] = 50,
	["EQP_STAT_SR_Petrification"] = 40,
	["EQP_STAT_SR_Poison"] = 50,
	["EQP_STAT_SR_Sleep"] = 15,
	["EQP_STAT_SR_Undead"] = 20,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Type"] = "Armor",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Dragonskin armor",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

