ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 200,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowAccuracy"] = true,
	["Attack_AllowDodge"] = true,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Speed"] = -99,
	["CausePoison"] = true,
	["Desc"] = "Much damage + poison/death! Great for training! Poisons user.",
	["EQP_STAT_ER_Flame"] = -25,
	["EQP_STAT_Power"] = 20,
	["EffectScript"] = "PoisonUser",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 15,
	["Stance"] = "Attack",
	["Target"] = "1F",
	["Title"] = "Venom Blade",
	["Type"] = "Item",
	["rew_GainSkill1"] = 19,
	["rew_GainSkill2"] = 20,
	["rew_GainSkill3"] = 20,
	["rew_GainSkill4"] = 20,
	["rew_GainSkill5"] = 20}

return ret

-- This file is an automatically generated file!

