ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "Raises power, but lowers defense",
	["EQP_STAT_Accuracy"] = 200,
	["EQP_STAT_Endurance"] = -1200,
	["EQP_STAT_Evasion"] = -200,
	["EQP_STAT_Power"] = 1200,
	["EQP_STAT_SR_Curse"] = 2,
	["EQP_STAT_SR_Death"] = 2,
	["EQP_STAT_SR_Destruction"] = 2,
	["EQP_STAT_SR_Disease"] = 2,
	["EQP_STAT_SR_Paralysis"] = 2,
	["EQP_STAT_SR_Petrification"] = 2,
	["EQP_STAT_SR_Poison"] = 2,
	["EQP_STAT_SR_Silence"] = 2,
	["EQP_STAT_SR_Sleep"] = 2,
	["EQP_STAT_SR_Undead"] = 2,
	["Heal_StatPercent"] = "Intelligence",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Accesoiry",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Ring of the tyrant",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

