ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 500,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowAccuracy"] = true,
	["Attack_AllowCritical"] = true,
	["Attack_AllowDodge"] = true,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Endurance"] = -100,
	["CauseParalysis"] = true,
	["Desc"] = "Extremly strong axe. Good for training. Drains user's life",
	["EQP_STAT_ER_Light"] = -25,
	["EffectScript"] = "EatUserHP",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Dandor",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 15,
	["Stance"] = "Attack",
	["Target"] = "1F",
	["Title"] = "Hungering Axe",
	["Type"] = "Item",
	["rew_GainSkill1"] = 15,
	["rew_GainSkill2"] = 15,
	["rew_GainSkill3"] = 15}

return ret

-- This file is an automatically generated file!

