ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "Now THIS is HOLY",
	["EQP_STAT_AP"] = 300,
	["EQP_STAT_ER_Darkness"] = -25,
	["EQP_STAT_ER_Earth"] = 5,
	["EQP_STAT_ER_Flame"] = 5,
	["EQP_STAT_ER_Frost"] = 5,
	["EQP_STAT_ER_Light"] = 200,
	["EQP_STAT_ER_Lightning"] = 10,
	["EQP_STAT_ER_Water"] = 5,
	["EQP_STAT_ER_Wind"] = 5,
	["EQP_STAT_Endurance"] = 100,
	["EQP_STAT_Evasion"] = 50,
	["EQP_STAT_HP"] = 1200,
	["EQP_STAT_Intelligence"] = 100,
	["EQP_STAT_Power"] = 1,
	["EQP_STAT_Resistance"] = 500,
	["EQP_STAT_SR_Curse"] = 50,
	["EQP_STAT_SR_Death"] = 40,
	["EQP_STAT_SR_Destruction"] = 30,
	["EQP_STAT_SR_Disease"] = 25,
	["EQP_STAT_SR_Paralysis"] = 25,
	["EQP_STAT_SR_Poison"] = 25,
	["EQP_STAT_SR_Silence"] = 25,
	["EQP_STAT_SR_Sleep"] = 10,
	["EQP_STAT_SR_Undead"] = 100,
	["Heal_StatPercent"] = "Intelligence",
	["ITM_ACC_HandoStillor"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "HandoStillor",
	["ITM_Field"] = true,
	["ITM_Type"] = "Armor",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Pope Robe",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

