ret = {
	["ABL_APCost"] = 150,
	["ADDCARD_Action_Act"] = "ABL_HERO_MARRILONA_CHILL",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Action_Number"] = 10,
	["Attack"] = 20,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Frost",
	["CauseSleep"] = true,
	["Desc"] = "The cold never bothered me anyway!",
	["EQP_STAT_Intelligence"] = 1,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 250,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["SpellAni"] = "Frost",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Iceblast",
	["Type"] = "Ability",
	["Voice"] = "Frost",
	["rew_CreateSkill1"] = true,
	["rew_GainSkill1"] = 5,
	["rew_GainSkill3"] = 100,
	["rew_GainSkill4"] = 100}

return ret

-- This file is an automatically generated file!

