ret = {
	["ABL_APCost"] = 250,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 75,
	["ADDCARD_Action_Number"] = 3,
	["Attack"] = 300,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Flame",
	["Desc"] = "We don't need no water, let the mother$(@*#@ burn!",
	["EQP_STAT_Intelligence"] = 1,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 2000,
	["ITM_Type"] = "Consumable",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 5,
	["SpellAni"] = "Inferno",
	["Stance"] = "Attack",
	["Target"] = "AF",
	["Title"] = "Inferno Orb",
	["Type"] = "Item",
	["Voice"] = "Fire",
	["rew_CreateSkill1"] = true,
	["rew_GainSkill1"] = 1,
	["rew_GainSkill2"] = 15}

return ret

-- This file is an automatically generated file!

