ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 9,
	["ADDCARD_Action_Number"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["CureCurse"] = true,
	["CureDisease"] = true,
	["CureParalysis"] = true,
	["CurePetrification"] = true,
	["CurePoison"] = true,
	["CureSilence"] = true,
	["CureSleep"] = true,
	["CureUndead"] = true,
	["Desc"] = "Heals all status ailments and adds extra cards doing the same",
	["Heal_StatPercent"] = "Intelligence",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 2500,
	["ITM_Type"] = "Consumable",
	["Revive"] = true,
	["Rew_GainAP"] = 5,
	["SpellAni"] = "AllHeal",
	["Stance"] = "Cast",
	["Target"] = "AA",
	["Title"] = "Purification Shower",
	["Type"] = "Item",
	["Voice"] = "Heal",
	["rew_GainSkill1"] = 5,
	["rew_GainSkill2"] = 5,
	["rew_GainSkill3"] = 5,
	["rew_GainSkill4"] = 5,
	["rew_GainSkill5"] = 5}

return ret

-- This file is an automatically generated file!

