ret = {
	["ABL_APCost"] = 250,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 50,
	["ADDCARD_Action_Number"] = 6,
	["Attack"] = 300,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Flame",
	["Desc"] = "Nobody can stop this fire",
	["EQP_STAT_Intelligence"] = 1,
	["EffectScript"] = "CurseUser",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 25000,
	["ITM_Type"] = "Consumable",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 5,
	["SpellAni"] = "Inferno",
	["Stance"] = "Cast",
	["Target"] = "AF",
	["Title"] = "Hell Stone",
	["Type"] = "Item",
	["Voice"] = "Fire",
	["rew_CreateSkill1"] = true,
	["rew_GainSkill1"] = 100,
	["rew_GainSkill2"] = 100,
	["rew_GainSkill3"] = 100,
	["rew_GainSkill4"] = 100,
	["rew_GainSkill5"] = 100}

return ret

-- This file is an automatically generated file!

