ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Accuracy"] = 25,
	["BUFF_Endurance"] = 25,
	["BUFF_Evasion"] = 25,
	["BUFF_Intelligence"] = 25,
	["BUFF_Power"] = 25,
	["BUFF_Resistance"] = 25,
	["BUFF_Speed"] = 25,
	["CureDisease"] = true,
	["CureParalysis"] = true,
	["CureSilence"] = true,
	["CureUndead"] = true,
	["Desc"] = "Tasty",
	["Heal"] = 50,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Percent",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 500,
	["ITM_Type"] = "Consumable",
	["Revive"] = true,
	["Rew_GainAP"] = 500,
	["SpellAni"] = "SingleHeal",
	["Stance"] = "Cast",
	["Target"] = "1A",
	["Title"] = "Mutton",
	["Type"] = "Item",
	["rew_GainSkill1"] = 500,
	["rew_GainSkill2"] = 8000,
	["rew_GainSkill3"] = 8000,
	["rew_GainSkill4"] = 8000,
	["rew_GainSkill5"] = 8000}

return ret

-- This file is an automatically generated file!

