ret = {
	["ABL_APCost"] = 50,
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 50,
	["ADDCARD_Action_Number"] = 2,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 200,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Water",
	["Desc"] = "World of water, where you swim to the other side",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 8000,
	["ITM_Type"] = "Consumable",
	["Rew_GainAP"] = 3,
	["SpellAni"] = "Tsunami",
	["Stance"] = "Cast",
	["Target"] = "AF",
	["Title"] = "Pocket Tsunami",
	["Type"] = "Item",
	["Voice"] = "Water",
	["rew_GainSkill1"] = 25,
	["rew_GainSkill2"] = 25,
	["rew_GainSkill3"] = 25,
	["rew_GainSkill4"] = 150,
	["rew_GainSkill5"] = 25}

return ret

-- This file is an automatically generated file!

