ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Action_Number"] = 15,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 500,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Accuracy"] = -1000,
	["BUFF_Endurance"] = -1000,
	["BUFF_Evasion"] = -1000,
	["BUFF_Intelligence"] = -1000,
	["BUFF_Power"] = -1000,
	["BUFF_Resistance"] = -1000,
	["BUFF_Speed"] = -1000,
	["Desc"] = "Oh they will BURN!",
	["Heal_StatPercent"] = "Intelligence",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 500000,
	["ITM_Type"] = "Consumable",
	["Rew_GainAP"] = 1000,
	["SpellAni"] = "Inferno",
	["Stance"] = "Cast",
	["Target"] = "AF",
	["Title"] = "Bottled Dragonfire",
	["Type"] = "Item",
	["Voice"] = "Flame",
	["rew_GainSkill1"] = 1000,
	["rew_GainSkill2"] = 1000,
	["rew_GainSkill3"] = 1000,
	["rew_GainSkill4"] = 1000,
	["rew_GainSkill5"] = 1000}

return ret

-- This file is an automatically generated file!

