ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Accuracy"] = -100,
	["BUFF_Endurance"] = -100,
	["BUFF_Evasion"] = -100,
	["BUFF_Intelligence"] = -100,
	["BUFF_Power"] = -100,
	["BUFF_Resistance"] = -100,
	["BUFF_Speed"] = -100,
	["CauseCurse"] = true,
	["CauseDeath"] = true,
	["CauseDisease"] = true,
	["CauseParalysis"] = true,
	["CausePoison"] = true,
	["CauseUndead"] = true,
	["Desc"] = "This disgusting stuff is supposed to be edible?",
	["EffectScript"] = "AlterPoints",
	["EffectScript_Arg"] = "HP1",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["Rew_GainAP"] = -10000000,
	["Stance"] = "Cast",
	["Target"] = "OS",
	["Title"] = "Sauerkraut",
	["Type"] = "Item",
	["rew_GainSkill1"] = -10000000,
	["rew_GainSkill2"] = -10000000,
	["rew_GainSkill3"] = -10000000,
	["rew_GainSkill4"] = -10000000,
	["rew_GainSkill5"] = -10000000}

return ret

-- This file is an automatically generated file!

