ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["BUFF_Accuracy"] = -100,
	["BUFF_Evasion"] = -100,
	["BUFF_Power"] = -100,
	["CauseCurse"] = true,
	["Desc"] = "This Trump curses the enemy.",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 666,
	["ITM_Type"] = "Consumable",
	["Rew_GainAP"] = 1,
	["SpellAni"] = "Heal",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Trump Card",
	["Type"] = "Item",
	["Voice"] = "Critical",
	["rew_GainSkill1"] = 1,
	["rew_GainSkill2"] = 1,
	["rew_GainSkill3"] = 1,
	["rew_GainSkill4"] = 1,
	["rew_GainSkill5"] = 1}

return ret

-- This file is an automatically generated file!

