ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Action_Number"] = 2,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 250,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowCritical"] = true,
	["Attack_AllowDodge"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "Physical attack on all targets",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 40000,
	["ITM_Type"] = "Consumable",
	["Rew_GainAP"] = 25,
	["Stance"] = "Cast",
	["Target"] = "AF",
	["Title"] = "Spike Bomb",
	["Type"] = "Item",
	["Voice"] = "Critical",
	["rew_GainSkill1"] = 10000,
	["rew_GainSkill2"] = 10000,
	["rew_GainSkill3"] = 10000,
	["rew_GainSkill4"] = 10000,
	["rew_GainSkill5"] = 10000}

return ret

-- This file is an automatically generated file!

