ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Action_Number"] = 200,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["Desc"] = "Elves LOVE these",
	["EffectScript"] = "RecoverAP",
	["EffectScript_Arg"] = "1",
	["Heal"] = 2,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Percent",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Consumable",
	["Rew_GainAP"] = 50,
	["SpellAni"] = "SingleHeal",
	["Stance"] = "Cast",
	["Target"] = "1A",
	["Title"] = "Yashar Berries",
	["Type"] = "Item",
	["rew_GainSkill1"] = 100,
	["rew_GainSkill2"] = 100,
	["rew_GainSkill3"] = 100,
	["rew_GainSkill4"] = 100,
	["rew_GainSkill5"] = 100}

return ret

-- This file is an automatically generated file!

