ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 100,
	["ADDCARD_Action_Number"] = 2,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["CureCurse"] = true,
	["CureDisease"] = true,
	["CureParalysis"] = true,
	["CurePetrification"] = true,
	["CurePoison"] = true,
	["CureSilence"] = true,
	["CureSleep"] = true,
	["CureUndead"] = true,
	["Desc"] = "Heal the entire party full and heal all status changes",
	["Heal"] = 100,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Percent",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 100000,
	["ITM_Type"] = "Consumable",
	["Revive"] = true,
	["Rew_GainAP"] = 100,
	["SpellAni"] = "AllHeal",
	["Stance"] = "Cast",
	["Target"] = "AA",
	["Title"] = "Ambrosia",
	["Type"] = "Item",
	["Voice"] = "Heal",
	["rew_GainSkill1"] = 25,
	["rew_GainSkill2"] = 25,
	["rew_GainSkill3"] = 25,
	["rew_GainSkill4"] = 25,
	["rew_GainSkill5"] = 25}

return ret

-- This file is an automatically generated file!

