ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 300,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowAccuracy"] = true,
	["Attack_AllowCritical"] = true,
	["Attack_AllowDodge"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "None",
	["BUFF_Endurance"] = -100,
	["CauseDeath"] = true,
	["Desc"] = "Kills the enemy, grants loads of skill exp. Curses user",
	["EQP_STAT_ER_Light"] = -25,
	["EQP_STAT_Evasion"] = 9,
	["EQP_STAT_Intelligence"] = 100,
	["EQP_STAT_Resistance"] = 70,
	["EQP_STAT_SR_Death"] = 100,
	["EffectScript"] = "CurseUser",
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_BlackMarket"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 15,
	["SpellAni"] = "SingleHeal",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Doom Wand",
	["Type"] = "Item",
	["Voice"] = "Hit",
	["rew_GainSkill1"] = 15,
	["rew_GainSkill2"] = 15,
	["rew_GainSkill3"] = 15,
	["rew_GainSkill4"] = 15,
	["rew_GainSkill5"] = 15}

return ret

-- This file is an automatically generated file!

