ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack"] = 125,
	["Attack_AccuracyRate"] = 100,
	["Attack_AllowAccuracy"] = true,
	["Attack_AllowCritical"] = true,
	["Attack_AllowDodge"] = true,
	["Attack_AttackStat"] = "Intelligence",
	["Attack_DefenseStat"] = "Resistance",
	["Attack_Element"] = "Frost",
	["BUFF_Evasion"] = -25,
	["Desc"] = "Only Trump's heart is colder",
	["EQP_STAT_Intelligence"] = 25,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Marrilona",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_ShopPrice"] = 123000,
	["ITM_Type"] = "Weapon",
	["ITM_WeaponAbility"] = true,
	["Rew_GainAP"] = 10,
	["Stance"] = "Attack",
	["Target"] = "AF",
	["Title"] = "Kelvin's Wand",
	["Type"] = "Item",
	["Voice"] = "Fire",
	["rew_GainSkill1"] = 25,
	["rew_GainSkill3"] = 12,
	["rew_GainSkill4"] = 12}

return ret

-- This file is an automatically generated file!

