ret = {
	["ADDCARD_Action_Act"] = "Self",
	["ADDCARD_Action_Interval"] = 5,
	["ADDCARD_Char_Interval"] = 5,
	["Attack_AccuracyRate"] = 100,
	["Attack_AttackStat"] = "Power",
	["Attack_DefenseStat"] = "Endurance",
	["Attack_Element"] = "None",
	["EQP_STAT_Accuracy"] = 5,
	["EQP_STAT_Endurance"] = 5,
	["EQP_STAT_Evasion"] = 5,
	["EQP_STAT_Intelligence"] = 5,
	["EQP_STAT_Power"] = 5,
	["EQP_STAT_Resistance"] = 5,
	["EQP_STAT_SR_Curse"] = 5,
	["EQP_STAT_SR_Death"] = 5,
	["EQP_STAT_SR_Destruction"] = 5,
	["EQP_STAT_SR_Disease"] = 5,
	["EQP_STAT_SR_Paralysis"] = 5,
	["EQP_STAT_SR_Petrification"] = 5,
	["EQP_STAT_SR_Poison"] = 5,
	["EQP_STAT_SR_Silence"] = 5,
	["EQP_STAT_SR_Sleep"] = 5,
	["EQP_STAT_SR_Undead"] = 5,
	["Heal_StatPercent"] = "Intelligence",
	["Heal_Type"] = "Absolute",
	["ITM_ACC_Dandor"] = true,
	["ITM_ACC_HandoStillor"] = true,
	["ITM_ACC_Jake"] = true,
	["ITM_ACC_Marrilona"] = true,
	["ITM_Combat"] = true,
	["ITM_EQP_For"] = "Jake",
	["ITM_Field"] = true,
	["ITM_Sellable"] = true,
	["ITM_Type"] = "Accesoiry",
	["Stance"] = "Cast",
	["Target"] = "1F",
	["Title"] = "Krandar's Armor",
	["Type"] = "Item"}

return ret

-- This file is an automatically generated file!

