-- This file has be generated by Tricky's MyData
-- 27 Dec 2016; 17:08:37



ret = {
	["ANNA"] = {
		["Dungeon"] = false,
		["Folder"] = "Delisto",
		["Kthura"] = "Anna",
		["Layer"] = "#001",
		["LocationName"] = "Anna's Temple",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["CH1ALTAR"] = {
		["Dungeon"] = false,
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_HUB_ALTAR",
		["Layer"] = "Altar",
		["LocationName"] = "Ancient Fairy Altar",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["CH1FRENDOR"] = {
		["Dungeon"] = false,
		["Folder"] = "Delisto",
		["Kthura"] = "PRO_Town_Frendor",
		["Layer"] = "town",
		["LocationName"] = "Frendor",
		["LocationPrefix"] = "The Fairy Village of",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["CH1FRENDORBUSHES"] = {
		["Dungeon"] = true,
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_Dungeon_FrendorBushes",
		["Layer"] = "FRENDORBUSHES",
		["LocationName"] = "Frendor Bushes",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true},
	["CH1HELL"] = {
		["Dungeon"] = true,
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_Dungeon_Hell",
		["Layer"] = "#001",
		["LocationName"] = "Road to Hell",
		["LocationPrefix"] = "The",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["CH1HOLY"] = {
		["Dungeon"] = true,
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_Dungeon_HolyPath",
		["Layer"] = "Bos",
		["LocationName"] = "Holy Path",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true},
	["CH1JAKE"] = {
		["Dungeon"] = false,
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_HUB_JakeHut",
		["Layer"] = "Exterior",
		["LocationName"] = "Jake's Hut",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true},
	["CH1LIBRARY"] = {
		["Dungeon"] = true,
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_Dungeon_Library",
		["Layer"] = "#001",
		["LocationName"] = "Forbidden Library",
		["LocationPrefix"] = "The",
		["Start"] = "Start",
		["UnlockedFromStart"] = false}}



-- Got all data, let's now return it!
return ret
