-- This file has be generated by Tricky's MyData
-- 06 Dec 2016; 23:32:06



ret = {
	["ANNA"] = {
		["Folder"] = "Delisto",
		["Kthura"] = "Anna",
		["Layer"] = "#001",
		["LocationName"] = "Anna's Temple",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = false},
	["CH1FRENDORBUSHES"] = {
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_Dungeon_FrendorBushes",
		["Layer"] = "#001",
		["LocationName"] = "Frendor Bushes",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true},
	["CH1HOLY"] = {
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_Dungeon_HolyPath",
		["Layer"] = "Bos",
		["LocationName"] = "Holy Path",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true},
	["CH1JAKE"] = {
		["Folder"] = "Delisto",
		["Kthura"] = "CH1_HUB_JakeHut",
		["Layer"] = "Exterior",
		["LocationName"] = "Jake's Hut",
		["LocationPrefix"] = "",
		["Start"] = "Start",
		["UnlockedFromStart"] = true}}



-- Got all data, let's now return it!
return ret
